name: Release Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Use project Node version from .nvmrc if present; falls back to 22.20.0
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        shell: pwsh
        run: |
          npm ci || npm install

      - name: Build Windows artifacts (NSIS and Portable)
        shell: pwsh
        env:
          # Provided automatically by GitHub; used later to upload assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder --win nsis portable --x64

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Upload the generated installers and metadata
          files: |
            dist/*.exe
            dist/*.blockmap
            dist/latest*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
